/*
 *==============================================================================
 * Name: soc_def_sim.h
 * Author: Martin Stankus
 *==============================================================================
 */

#ifndef _SOC_DEF_SIM_H_
#define _SOC_DEF_SIM_H_

#define SIM_SOPT1_OSC32KSEL_VAL_OSC32KCLK	0u
#define SIM_SOPT1_OSC32KSEL_VAL_RTC_CLKIN	2u
#define SIM_SOPT1_OSC32KSEL_VAL_LPOCLK		3u

#define SIM_SOPT2_UART0SRC_VAL_DIS			0u
#define SIM_SOPT2_UART0SRC_VAL_MCGPLLCLK	1u
#define SIM_SOPT2_UART0SRC_VAL_OSCERCLK		2u
#define SIM_SOPT2_UART0SRC_VAL_MCGIRCLK		3u

#define SIM_SOPT2_TPMSRC_VAL_DIS			0u
#define SIM_SOPT2_TPMSRC_VAL_MCGPLLCLK		1u
#define SIM_SOPT2_TPMSRC_VAL_OSCERCLK		2u
#define SIM_SOPT2_TPMSRC_VAL_MCGIRCLK		3u

#define SIM_SOPT2_CLKOUTSEL_VAL_BUSCLK		2u
#define SIM_SOPT2_CLKOUTSEL_VAL_LPOCLK		3u
#define SIM_SOPT2_CLKOUTSEL_VAL_MCGIRCLK	4u
#define SIM_SOPT2_CLKOUTSEL_VAL_OSCERCLK	6u

#define SIM_SOPT7_ADTGSL_VAL_ETG_IN			0u
#define SIM_SOPT7_ADTGSL_VAL_CMP0			1u
#define SIM_SOPT7_ADTGSL_VAL_PIT0			4u
#define SIM_SOPT7_ADTGSL_VAL_PIT1			5u
#define SIM_SOPT7_ADTGSL_VAL_TPM0			8u
#define SIM_SOPT7_ADTGSL_VAL_TPM1			9u
#define SIM_SOPT7_ADTGSL_VAL_TPM2			10u
#define SIM_SOPT7_ADTGSL_VAL_RTC_ALR		12u
#define SIM_SOPT7_ADTGSL_VAL_RTC_SEC		13u
#define SIM_SOPT7_ADTGSL_VAL_LPTMR0			14u

#define SIM_CLKDIV1_OUTDIV1_VAL_D1			0u
#define SIM_CLKDIV1_OUTDIV1_VAL_D2			1u
#define SIM_CLKDIV1_OUTDIV1_VAL_D3			2u
#define SIM_CLKDIV1_OUTDIV1_VAL_D4			3u
#define SIM_CLKDIV1_OUTDIV1_VAL_D5			4u
#define SIM_CLKDIV1_OUTDIV1_VAL_D6			5u
#define SIM_CLKDIV1_OUTDIV1_VAL_D7			6u
#define SIM_CLKDIV1_OUTDIV1_VAL_D8			7u
#define SIM_CLKDIV1_OUTDIV1_VAL_D9			8u
#define SIM_CLKDIV1_OUTDIV1_VAL_D10			9u
#define SIM_CLKDIV1_OUTDIV1_VAL_D11			10u
#define SIM_CLKDIV1_OUTDIV1_VAL_D12			11u
#define SIM_CLKDIV1_OUTDIV1_VAL_D13			12u
#define SIM_CLKDIV1_OUTDIV1_VAL_D14			13u
#define SIM_CLKDIV1_OUTDIV1_VAL_D15			14u
#define SIM_CLKDIV1_OUTDIV1_VAL_D16			15u

#define SIM_CLKDIV1_OUTDIV4_VAL_D1			0u
#define SIM_CLKDIV1_OUTDIV4_VAL_D2			1u
#define SIM_CLKDIV1_OUTDIV4_VAL_D3			2u
#define SIM_CLKDIV1_OUTDIV4_VAL_D4			3u
#define SIM_CLKDIV1_OUTDIV4_VAL_D5			4u
#define SIM_CLKDIV1_OUTDIV4_VAL_D6			5u
#define SIM_CLKDIV1_OUTDIV4_VAL_D7			6u
#define SIM_CLKDIV1_OUTDIV4_VAL_D8			7u

#endif /* _SOC_DEF_SIM_H_ */
