/*
 *==============================================================================
 * Name: init.c
 * Author: Martin Stankus
 *==============================================================================
 */

#include "mkl25z4.h"

#include "init.h"
#include "soc_def.h"
#include "bme.h"

void init(void)
{
	SIM->CLKDIV1 = 0ul;

	//FEI to FBI

	MCG->SC = 0u;
	MCG->C2 = MCG_C2_IRCS_MASK;
	MCG->C1 = MCG_C1_CLKS(MCG_C1_CLKS_VAL_INT) | MCG_C1_IREFS_MASK;

	while (BME_UBFX_B(&MCG->S, MCG_S_CLKST_SHIFT, 2u) != MCG_S_CLKST_VAL_INT);

	//FBI to BLPI

	MCG->C2 = MCG_C2_LP_MASK | MCG_C2_IRCS_MASK;
	MCG->C1 = MCG_C1_CLKS(MCG_C1_CLKS_VAL_INT) | MCG_C1_IREFS_MASK | MCG_C1_IRCLKEN_MASK;

	SIM->SCGC4 = SIM_SCGC4_SPI1_MASK | SIM_SCGC4_SPI0_MASK | SIM_SCGC4_UART1_MASK | SIM_SCGC4_I2C1_MASK;
	SIM->SCGC5 = SIM_SCGC5_PORTE_MASK | SIM_SCGC5_PORTD_MASK | SIM_SCGC5_PORTC_MASK |
				SIM_SCGC5_PORTB_MASK | SIM_SCGC5_PORTA_MASK;
	SIM->SCGC6 = SIM_SCGC6_ADC0_MASK | SIM_SCGC6_TPM2_MASK | SIM_SCGC6_TPM1_MASK | SIM_SCGC6_TPM0_MASK |
				SIM_SCGC6_PIT_MASK | SIM_SCGC6_DMAMUX_MASK | SIM_SCGC6_FTF_MASK;
	SIM->SCGC7 = SIM_SCGC7_DMA_MASK;

	SIM->SOPT1 = SIM_SOPT1_OSC32KSEL(SIM_SOPT1_OSC32KSEL_VAL);
	SIM->SOPT2 = SIM_SOPT2_UART0SRC(SIM_SOPT2_UART0SRC_VAL) | SIM_SOPT2_TPMSRC(SIM_SOPT2_TPMSRC_VAL) |
				SIM_SOPT2_CLKOUTSEL(SIM_SOPT2_CLKOUTSEL_VAL);

	SIM->CLKDIV1 = SIM_CLKDIV1_OUTDIV1(SIM_CLKDIV1_OUTDIV1_VAL) |
				SIM_CLKDIV1_OUTDIV4(SIM_CLKDIV1_OUTDIV4_VAL);

#if VLP
	//RUN to VLPR

	SMC->PMPROT = SMC_PMPROT_AVLP_MASK;
	SMC->PMCTRL = SMC_PMCTRL_RUNM(SMC_PMCTRL_RUNM_VAL_VLPR) |
				SMC_PMCTRL_STOPM(SMC_PMCTRL_STOPM_VAL_VLPS);

	while (SMC->PMSTAT != SMC_PMSTAT_VAL_VLPR);
# endif
}
