/*
 *==============================================================================
 * Name: brd_def_io.h
 * Author: Martin Stankus
 *==============================================================================
 */

#ifndef _BRD_DEF_IO_H_
#define _BRD_DEF_IO_H_

#include "mkl25z4.h"

#include "soc_def.h"

#define PORT_HEX_SW				PORTE
#define GPIO_HEX_SW				GPIOE
#define FGPIO_HEX_SW			FGPIOE
#define IOIND_HEX_SW			2u
#define IOMASK_HEX_SW			(0xFul << IOIND_HEX_SW)
#define GPCR_HEX_SW				PORT_HEX_SW->GPCLR

#define PORT_BTN_SW1			PORTD
#define GPIO_BTN_SW1			GPIOD
#define FGPIO_BTN_SW1			FGPIOD
#define IOIND_BTN_SW1			7u
#define IOMASK_BTN_SW1			(1ul << IOIND_BTN_SW1)
#define IRQN_BTN_SW1			PORTD_IRQn

#define PORT_BTN_SW2			PORTD
#define GPIO_BTN_SW2			GPIOD
#define FGPIO_BTN_SW2			FGPIOD
#define IOIND_BTN_SW2			6u
#define IOMASK_BTN_SW2			(1ul << IOIND_BTN_SW2)
#define IRQN_BTN_SW2			PORTD_IRQn

#define PORT_LED_D1				PORTB
#define GPIO_LED_D1				GPIOB
#define FGPIO_LED_D1			FGPIOB
#define IOIND_LED_D1			19u
#define IOMASK_LED_D1			(1ul << IOIND_LED0)

#define PORT_LED_D2				PORTB
#define GPIO_LED_D2				GPIOB
#define FGPIO_LED_D2			FGPIOB
#define IOIND_LED_D2			18u
#define IOMASK_LED_D2			(1ul << IOIND_LED1)

#define PORT_UART_COM_TX		PORTE
#define GPIO_UART_COM_TX		GPIOE
#define FGPIO_UART_COM_TX		FGPIOE
#define IOIND_UART_COM_TX		0u
#define IOMASK_UART_COM_TX		(1ul << IOIND_UART_COM_TX)
#define MUX_UART_COM_TX			PORT_PCR_MUX_VAL_ALT3

#define PORT_UART_COM_RX		PORTE
#define GPIO_UART_COM_RX		GPIOE
#define FGPIO_UART_COM_RX		FGPIOE
#define IOIND_UART_COM_RX		1u
#define IOMASK_UART_COM_RX		(1ul << IOIND_UART_COM_RX)
#define MUX_UART_COM_RX			PORT_PCR_MUX_VAL_ALT3

#define PORT_SPI_LORA_MOSI		PORTB
#define GPIO_SPI_LORA_MOSI		GPIOB
#define FGPIO_SPI_LORA_MOSI		FGPIOB
#define IOIND_SPI_LORA_MOSI		17u
#define IOMASK_SPI_LORA_MOSI	(1ul << IOIND_SPI_LORA_MOSI)
#define MUX_SPI_LORA_MOSI		PORT_PCR_MUX_VAL_ALT5

#define PORT_SPI_LORA_MISO		PORTB
#define GPIO_SPI_LORA_MISO		GPIOB
#define FGPIO_SPI_LORA_MISO		FGPIOB
#define IOIND_SPI_LORA_MISO		16u
#define IOMASK_SPI_LORA_MISO	(1ul << IOIND_SPI_LORA_MISO)
#define MUX_SPI_LORA_MISO		PORT_PCR_MUX_VAL_ALT5

#define PORT_SPI_LORA_SCK		PORTB
#define GPIO_SPI_LORA_SCK		GPIOB
#define FGPIO_SPI_LORA_SCK		FGPIOB
#define IOIND_SPI_LORA_SCK		11u
#define IOMASK_SPI_LORA_SCK		(1ul << IOIND_SPI_LORA_SCK)
#define MUX_SPI_LORA_SCK		PORT_PCR_MUX_VAL_ALT2

#define PORT_SPI_LORA_CS		PORTB
#define GPIO_SPI_LORA_CS		GPIOB
#define FGPIO_SPI_LORA_CS		FGPIOB
#define IOIND_SPI_LORA_CS		10u
#define IOMASK_SPI_LORA_CS		(1ul << IOIND_SPI_LORA_CS)
#define MUX_SPI_LORA_CS			PORT_PCR_MUX_VAL_ALT2

#define PORT_LORA_DIO1			PORTA
#define GPIO_LORA_DIO1			GPIOA
#define FGPIO_LORA_DIO1			FGPIOA
#define IOIND_LORA_DIO1			4u
#define IOMASK_LORA_DIO1		(1ul << IOIND_LORA_DIO1)
#define IRQN_LORA_DIO1			PORTA_IRQn

#define PORT_LORA_BUSY			PORTA
#define GPIO_LORA_BUSY			GPIOA
#define FGPIO_LORA_BUSY			FGPIOA
#define IOIND_LORA_BUSY			5u
#define IOMASK_LORA_BUSY		(1ul << IOIND_LORA_BUSY)

#define PORT_LORA_PWR_CTRL		PORTC
#define GPIO_LORA_PWR_CTRL		GPIOC
#define FGPIO_LORA_PWR_CTRL		FGPIOC
#define IOIND_LORA_PWR_CTRL		13u
#define IOMASK_LORA_PWR_CTRL	(1ul << IOIND_LORA_PWR_CTRL)

#define PORT_LORA_NRST			PORTC
#define GPIO_LORA_NRST			GPIOC
#define FGPIO_LORA_NRST			FGPIOC
#define IOIND_LORA_NRST			2u
#define IOMASK_LORA_NRST		(1ul << IOIND_LORA_NRST)

#define PORT_SPI_SENS_MOSI		PORTA
#define GPIO_SPI_SENS_MOSI		GPIOA
#define FGPIO_SPI_SENS_MOSI		FGPIOA
#define IOIND_SPI_SENS_MOSI		16u
#define IOMASK_SPI_SENS_MOSI	(1ul << IOIND_SPI_SENS_MOSI)
#define MUX_SPI_SENS_MOSI		PORT_PCR_MUX_VAL_ALT2

#define PORT_SPI_SENS_MISO		PORTA
#define GPIO_SPI_SENS_MISO		GPIOA
#define FGPIO_SPI_SENS_MISO		FGPIOA
#define IOIND_SPI_SENS_MISO		17u
#define IOMASK_SPI_SENS_MISO	(1ul << IOIND_SPI_SENS_MISO)
#define MUX_SPI_SENS_MISO		PORT_PCR_MUX_VAL_ALT2

#define PORT_SPI_SENS_SCK		PORTA
#define GPIO_SPI_SENS_SCK		GPIOA
#define FGPIO_SPI_SENS_SCK		FGPIOA
#define IOIND_SPI_SENS_SCK		15u
#define IOMASK_SPI_SENS_SCK		(1ul << IOIND_SPI_SENS_SCK)
#define MUX_SPI_SENS_SCK		PORT_PCR_MUX_VAL_ALT2

#define PORT_SPI_SENS_CS		PORTA
#define GPIO_SPI_SENS_CS		GPIOA
#define FGPIO_SPI_SENS_CS		FGPIOA
#define IOIND_SPI_SENS_CS		14u
#define IOMASK_SPI_SENS_CS		(1ul << IOIND_SPI_SENS_CS)
#define MUX_SPI_SENS_CS			PORT_PCR_MUX_VAL_ALT2

#define PORT_SENS_INT			PORTA
#define GPIO_SENS_INT			GPIOA
#define FGPIO_SENS_INT			FGPIOA
#define IOIND_SENS_INT			13u
#define IOMASK_SENS_INT			(1ul << IOIND_SENS_INT)
#define IRQN_SENS_INT			PORTA_IRQn

#define PORT_IIC_EEPROM_SDA		PORTC
#define GPIO_IIC_EEPROM_SDA		GPIOC
#define FGPIO_IIC_EEPROM_SDA	FGPIOC
#define IOIND_IIC_EEPROM_SDA	11u
#define IOMASK_IIC_EEPROM_SDA	(1ul << IOIND_IIC_EEPROM_SDA)
#define MUX_IIC_EEPROM_SDA		PORT_PCR_MUX_VAL_ALT2

#define PORT_IIC_EEPROM_SCL		PORTC
#define GPIO_IIC_EEPROM_SCL		GPIOC
#define FGPIO_IIC_EEPROM_SCL	FGPIOC
#define IOIND_IIC_EEPROM_SCL	10u
#define IOMASK_IIC_EEPROM_SCL	(1ul << IOIND_IIC_EEPROM_SCL)
#define MUX_IIC_EEPROM_SCL		PORT_PCR_MUX_VAL_ALT2

#define PORT_EEPROM_PWR_CTRL	PORTC
#define GPIO_EEPROM_PWR_CTRL	GPIOC
#define FGPIO_EEPROM_PWR_CTRL	FGPIOC
#define IOIND_EEPROM_PWR_CTRL	12u
#define IOMASK_EEPROM_PWR_CTRL	(1ul << IOIND_EEPROM_PWR_CTRL)

#define PORT_CLKOUT				PORTC
#define IOIND_CLKOUT			3u
#define MUX_CLKOUT				PORT_PCR_MUX_VAL_ALT5

//SENS PIN 51
#define PORT_MARKER_A			PORTC
#define GPIO_MARKER_A			GPIOC
#define FGPIO_MARKER_A			FGPIOC
#define IOIND_MARKER_A			9u
#define IOMASK_MARKER_A			(1ul << IOIND_MARKER_A)

//SENS PIN 53
#define PORT_MARKER_B			PORTC
#define GPIO_MARKER_B			GPIOC
#define FGPIO_MARKER_B			FGPIOC
#define IOIND_MARKER_B			8u
#define IOMASK_MARKER_B			(1ul << IOIND_MARKER_B)

//SENS PIN 55
#define PORT_MARKER_C			PORTC
#define GPIO_MARKER_C			GPIOC
#define FGPIO_MARKER_C			FGPIOC
#define IOIND_MARKER_C			7u
#define IOMASK_MARKER_C			(1ul << IOIND_MARKER_C)

//SENS PIN 57
#define PORT_MARKER_D			PORTC
#define GPIO_MARKER_D			GPIOC
#define FGPIO_MARKER_D			FGPIOC
#define IOIND_MARKER_D			6u
#define IOMASK_MARKER_D			(1ul << IOIND_MARKER_D)

//SENS PIN 59
#define PORT_MARKER_E			PORTC
#define GPIO_MARKER_E			GPIOC
#define FGPIO_MARKER_E			FGPIOC
#define IOIND_MARKER_E			5u
#define IOMASK_MARKER_E			(1ul << IOIND_MARKER_E)

//SENS PIN 61
#define PORT_MARKER_F			PORTC
#define GPIO_MARKER_F			GPIOC
#define FGPIO_MARKER_F			FGPIOC
#define IOIND_MARKER_F			4u
#define IOMASK_MARKER_F			(1ul << IOIND_MARKER_F)

#endif /* _BRD_DEF_IO_H_ */
